// templates/expo/App.tsx
import "text-encoding-polyfill";
import "react-native-get-random-values";
import { Buffer } from "buffer";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Dimensions, StyleSheet, Text, View } from "react-native";
import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  TransactionMessage,
  VersionedTransaction,
} from "@solana/web3.js";
import { CoinflowPurchase } from "@coinflowlabs/react-native";
import {
  createTransferCheckedInstruction,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { sign } from "tweetnacl";

global.Buffer = Buffer;

export default function App() {
  const [keypair, setKeypair] = useState<Keypair>(
    Keypair.fromSecretKey(
      Uint8Array.from([
        135, 172, 8, 68, 115, 157, 189, 112, 178, 17, 122, 230, 130, 245, 69,
        180, 20, 92, 216, 188, 190, 6, 163, 202, 177, 120, 104, 193, 78, 153,
        236, 176, 193, 185, 18, 86, 88, 18, 97, 29, 212, 65, 153, 129, 197, 0,
        179, 89, 27, 150, 198, 91, 214, 235, 151, 47, 81, 119, 37, 254, 157,
        203, 238, 174,
      ])
    )
  );
  const publicKey = useMemo(() => {
    return keypair.publicKey;
  }, [keypair]);

  useEffect(() => {
    console.log(publicKey.toString());
  }, []);

  const connection = useMemo(
    () => new Connection("https://api.devnet.solana.com", "confirmed"),
    []
  );

  const sendTransaction = useCallback(
    async (transaction: Transaction | VersionedTransaction) => {
      if ("instructions" in transaction) {
        console.log("Regular Transaction");
        transaction.feePayer = publicKey;
        console.log("Regular Transaction 1");
        transaction.signatures = [];
        transaction.sign(keypair);
        console.log("Regular Transaction 2");
      } else {
        console.log("VersionedTransaction!!!!!");
        console.log(transaction);
        try {
          transaction.message.staticAccountKeys[0] = keypair.publicKey;
          transaction.signatures = [];
          transaction.signatures[0] = Buffer.alloc(64, 0);
          transaction.sign([keypair]);
        } catch (e) {
          console.error(e);
          throw e;
        }
      }
      console.log("done signing!!!!!");
      console.log(Buffer.from(transaction.serialize()).toString("base64"));
      const sig = await connection.sendRawTransaction(transaction.serialize());
      console.log({ sig });
      return sig;
    },
    []
  );

  const signMessage = async (message: Uint8Array) => {
    console.log("signMessage!!!!!!");
    return Promise.resolve(sign.detached(message, keypair.secretKey));
  };

  const transaction = useMemo(() => {
    const mint = new PublicKey("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU");

    const receiver = new PublicKey(
      "H191L17jE26R1wGWQHAx5KQhBwSwHPMgzb2A66Hr9h37"
    );

    const receiverAta = getAssociatedTokenAddressSync(mint, receiver);

    const transferAmount = Number(1 / 2) * Math.pow(10, 6);
    const transferIx1 = createTransferCheckedInstruction(
      new PublicKey("33333333333333333333333333333333333333333333"),
      mint,
      receiverAta,
      new PublicKey("22222222222222222222222222222222222222222222"),
      transferAmount,
      6
    );
    const transferIx2 = createTransferCheckedInstruction(
      new PublicKey("33333333333333333333333333333333333333333333"),
      mint,
      new PublicKey("HzdseyCGneNv4SzyBgteppi1N8GawjWLSkBSTx82UTtL"),
      new PublicKey("22222222222222222222222222222222222222222222"),
      transferAmount,
      6
    );
    const message = new TransactionMessage({
      payerKey: Keypair.generate().publicKey,
      recentBlockhash: Keypair.generate().publicKey.toString(),
      instructions: [transferIx1, transferIx2],
    }).compileToV0Message();
    return new VersionedTransaction(message);
  }, []);

  return (
    <View style={styles.container}>
      <View>
        <Text>Public key: {publicKey?.toString()}</Text>
        {/*<CoinflowWithdraw*/}
        {/*  style={styles.container}*/}
        {/*  wallet={{*/}
        {/*    publicKey,*/}
        {/*    sendTransaction,*/}
        {/*    signMessage,*/}
        {/*  }}*/}
        {/*  merchantId={"paysafe"}*/}
        {/*  connection={connection}*/}
        {/*  blockchain={"solana"}*/}
        {/*  env={"local"}*/}
        {/*/>*/}
        <CoinflowPurchase
          style={styles.container}
          wallet={{
            publicKey,
            sendTransaction,
            signMessage,
          }}
          merchantId={"paysafe"}
          connection={connection}
          blockchain={"solana"}
          env={"local"}
          amount={1}
          disableApplePay={true}
          transaction={transaction}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 50,
    paddingBottom: 30,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  consoleArea: {
    margin: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  console: {
    flex: 1,
    backgroundColor: "#CCCCCC",
    color: "#ffffff",
    padding: 10,
    width: Dimensions.get("window").width - 60,
  },
  consoleText: {
    padding: 10,
  },
  buttonArea: {
    flex: 2,
    alignItems: "center",
    justifyContent: "space-around",
    paddingBottom: 30,
  },
});

// examples/vue/solana/withdraw/src/App.vue
<script setup lang="ts">
import { Connection, Keypair, Transaction, VersionedTransaction } from "@solana/web3.js";
import { sign } from "tweetnacl";
import { ref } from "vue";
import { CoinflowWithdraw } from "@coinflowlabs/vue";

const height = ref(500);
const handleHeightChange = (newHeight: string) => {
  height.value = Number(newHeight);
};
const merchantId = process.env.VITE_MERCHANT_ID as string;
const keypair = Keypair.fromSecretKey(
  Uint8Array.from([
    56, 14, 246, 208, 184, 212, 110, 37, 164, 242, 149, 110, 238, 115, 65,
    243, 91, 159, 62, 192, 243, 4, 84, 48, 19, 210, 63, 37, 208, 36, 158, 61,
    242, 18, 206, 253, 243, 8, 213, 146, 146, 126, 125, 217, 207, 28, 77, 218,
    206, 8, 210, 3, 70, 26, 82, 213, 209, 139, 197, 120, 5, 103, 102, 171,
  ])
);
const sendTransaction = (tx: Transaction | VersionedTransaction) => {
  const connection = new Connection('https://api.devnet.solana.com');
  if ('recentBlockhash' in tx) {
    tx.partialSign(keypair);
  } else {
    (tx as VersionedTransaction).sign([keypair]);
  }
  return connection.sendRawTransaction(tx.serialize(), {skipPreflight: true});
};
const signMessage = (message: Uint8Array) => {
  return Promise.resolve(sign.detached(message, keypair.secretKey));
};
</script>

<template>
  <div :style="{width: '100%', height: `${height}px`}">
    <CoinflowWithdraw :args="{
        wallet: {
          publicKey: keypair.publicKey,
          sendTransaction,
          signMessage,
        },
        env: 'sandbox',
        blockchain: 'solana',
        merchantId: merchantId,
        connection: new Connection('https://api.devnet.solana.com'),
        handleHeightChange,
      }"
    />
  </div>
</template>

<style scoped>
div {
  width: 100%;
}
</style>
