// examples/react/polygon/checkout/src/App.tsx
import React, {useEffect, useState} from 'react';
import {CoinflowEnvs, CoinflowPurchase} from '@coinflowlabs/react';
import {usePolygonWallet, Wallet} from './Wallet';
import {Web3Button} from '@web3modal/react';
import {providers} from 'ethers';
import {UsdcWrapper__factory} from './generated';

function App() {
  return (
    <Wallet>
      <div className="App">
        <Web3Button />
        <div
          style={{
            height: '100vh',
          }}
        >
          <CoinflowContent />
        </div>
      </div>
    </Wallet>
  );
}

function CoinflowContent() {
  const wallet = usePolygonWallet();

  const [tx, setTx] = useState<
    (providers.TransactionRequest & {to: string}) | undefined
  >(undefined);

  const amount = 1;

  useEffect(() => {
    async function initializeTx() {
      if (!wallet.address) return;

      const tx = (await UsdcWrapper__factory.connect(
        '0x0E47E1CC9730bf1CaC4fb2073e04Dc60Faf3fdDe',
        new providers.JsonRpcProvider(
          process.env.REACT_APP_POLYGON_RPC_URL as string
        )
      ).populateTransaction.buyWusdcWithWethModifiedReceiver(
        amount * 1e6,
        wallet.address,
        {
          from: wallet.address,
        }
      )) as providers.TransactionRequest & {to: string};
      setTx(tx);
    }

    initializeTx();
  }, [amount, wallet.address, wallet.sendTransaction]);

  if (!wallet?.address) return null;

  return (
    <CoinflowPurchase
      wallet={wallet}
      merchantId={process.env.REACT_APP_MERCHANT_ID as string}
      env={process.env.REACT_APP_ENV as CoinflowEnvs}
      onSuccess={() => console.log('Withdraw Success')}
      blockchain={'polygon'}
      transaction={tx}
      amount={1}
    />
  );
}

export default App;

// examples/vue/polygon/withdraw/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { CoinflowWithdraw } from "@coinflowlabs/vue";
import { ethers } from "ethers";

const height = ref(500);
const handleHeightChange = (newHeight: string) => {
  height.value = Number(newHeight);
};

const merchantId = import.meta.env.VITE_MERCHANT_ID as string;
const privateKey = import.meta.env.VITE_WALLET_PRIVATE_KEY as string;
const rpcUrl = import.meta.env.VITE_RPC_URL as string;
const provider = new ethers.providers.JsonRpcProvider(rpcUrl);
const wallet = new ethers.Wallet(privateKey, provider);

console.log("Ethereum wallet address:", wallet.address);

const sendTransaction = async (transaction: ethers.providers.TransactionRequest & { to: string }): Promise<{hash: string}> => {
  const signedTransaction = await wallet.signTransaction(transaction);
    const txResponse = await provider.sendTransaction(signedTransaction);
    const {hash} = txResponse;
    return {hash};
};

 const signMessage = async (message: string): Promise<string> => {
    return await wallet.signMessage(message);
  };
</script>

<template>
  <div :style="{width: '100%', height: `${height}px`}">
    <CoinflowWithdraw :args="{
        wallet: {
          address: wallet.address,
          sendTransaction,
          signMessage,
        },
        env: 'sandbox',
        blockchain: 'polygon',
        merchantId: merchantId,
        handleHeightChange,
      }"
    />
  </div>
</template>

<style scoped>
div {
  width: 100%;
}
</style>
