// examples/vue/solana/checkout/src/App.vue
<script setup lang="ts">
import { Connection, Keypair, Transaction, VersionedTransaction } from "@solana/web3.js";
import { sign } from "tweetnacl";
import { ref } from "vue";
import { CoinflowPurchase } from "@coinflowlabs/vue";

const height = ref(500);
const handleHeightChange = (newHeight: string) => {
  height.value = Number(newHeight);
};

const keypair = Keypair.fromSecretKey(
  Uint8Array.from([
    56, 14, 246, 208, 184, 212, 110, 37, 164, 242, 149, 110, 238, 115, 65,
    243, 91, 159, 62, 192, 243, 4, 84, 48, 19, 210, 63, 37, 208, 36, 158, 61,
    242, 18, 206, 253, 243, 8, 213, 146, 146, 126, 125, 217, 207, 28, 77, 218,
    206, 8, 210, 3, 70, 26, 82, 213, 209, 139, 197, 120, 5, 103, 102, 171,
  ])
);
const sendTransaction = (tx: Transaction | VersionedTransaction) => {
  const connection = new Connection('https://api.devnet.solana.com');
  if ('recentBlockhash' in tx) {
    tx.partialSign(keypair);
  } else {
    (tx as VersionedTransaction).sign([keypair]);
  }
  return connection.sendRawTransaction(tx.serialize(), {skipPreflight: true});
};
const signMessage = (message: Uint8Array) => {
  return Promise.resolve(sign.detached(message, keypair.secretKey));
};
</script>

<template>
  <div :style="{width: '100%', height: `${height}px`}">
    <CoinflowPurchase :args="{
        wallet: {
          publicKey: keypair.publicKey,
          sendTransaction,
          signMessage,
        },
        env: 'sandbox',
        blockchain: 'solana',
        merchantId: 'paysafe',
        connection: new Connection('https://api.devnet.solana.com'),
        handleHeightChange,
      }"
    />
  </div>
</template>

<style scoped>
div {
  width: 100%;
}
</style>

// templates/expo/App.tsx
import "text-encoding-polyfill";
import "react-native-get-random-values";
import { Buffer } from "buffer";
import React, { useCallback, useMemo, useState } from "react";
import { Dimensions, StyleSheet, Text, View } from "react-native";
import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  VersionedTransaction,
} from "@solana/web3.js";
import { CoinflowPurchase } from "@coinflowlabs/react-native";
import {
  createTransferCheckedInstruction,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { sign } from "tweetnacl";

global.Buffer = Buffer;

export default function App() {
  const [keypair, setKeypair] = useState<Keypair>(Keypair.generate());
  const publicKey = useMemo(() => {
    return keypair.publicKey;
  }, [keypair]);

  const connection = useMemo(
    () => new Connection("https://api.devnet.solana.com", "confirmed"),
    []
  );

  const sendTransaction = useCallback(
    async (transaction: Transaction | VersionedTransaction) => {
      if ("instructions" in transaction) {
        console.log("Regular Transaction");
        // transaction.feePayer = publicKey;
        transaction.partialSign(keypair);
      } else {
        console.log("VersionedTransaction!!!!!");
        console.log(transaction);
        try {
          transaction.sign([keypair]);
        } catch (e) {
          console.error(e);
          throw e;
        }
      }
      console.log("done signing!!!!!");
      console.log(transaction.serialize().toString("base64"));
      const sig = await connection.sendRawTransaction(transaction.serialize());
      console.log({ sig });
      return sig;
    },
    []
  );

  const signMessage = async (message: Uint8Array) => {
    console.log("signMessage!!!!!!");
    return Promise.resolve(sign.detached(message, keypair.secretKey));
  };

  const transaction = useMemo(() => {
    const mint = new PublicKey("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU");

    const receiver = new PublicKey(
      "H191L17jE26R1wGWQHAx5KQhBwSwHPMgzb2A66Hr9h37"
    );

    const receiverAta = getAssociatedTokenAddressSync(mint, receiver);

    const transferAmount = Number(1 / 2) * Math.pow(10, 6);
    const transferIx1 = createTransferCheckedInstruction(
      new PublicKey("33333333333333333333333333333333333333333333"),
      mint,
      receiverAta,
      new PublicKey("22222222222222222222222222222222222222222222"),
      transferAmount,
      6
    );
    const transferIx2 = createTransferCheckedInstruction(
      new PublicKey("33333333333333333333333333333333333333333333"),
      mint,
      new PublicKey("HzdseyCGneNv4SzyBgteppi1N8GawjWLSkBSTx82UTtL"),
      new PublicKey("22222222222222222222222222222222222222222222"),
      transferAmount,
      6
    );
    return new Transaction({
      feePayer: Keypair.generate().publicKey,
      blockhash: Keypair.generate().publicKey.toString(),
      lastValidBlockHeight: 1,
    }).add(transferIx1, transferIx2);
  }, []);

  return (
    <View style={styles.container}>
      <View>
        <Text>Public key: {publicKey?.toString()}</Text>
        <CoinflowPurchase
          style={styles.container}
          wallet={{
            publicKey,
            sendTransaction,
            signMessage,
          }}
          merchantId={"paysafe"}
          connection={connection}
          blockchain={"solana"}
          env={"local"}
          amount={1}
          disableApplePay={true}
          transaction={transaction}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 50,
    paddingBottom: 30,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  consoleArea: {
    margin: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  console: {
    flex: 1,
    backgroundColor: "#CCCCCC",
    color: "#ffffff",
    padding: 10,
    width: Dimensions.get("window").width - 60,
  },
  consoleText: {
    padding: 10,
  },
  buttonArea: {
    flex: 2,
    alignItems: "center",
    justifyContent: "space-around",
    paddingBottom: 30,
  },
});
