// examples/vue/base/checkout/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { CoinflowPurchase } from "@coinflowlabs/vue";
import { ethers } from "ethers";

const height = ref(500);
const handleHeightChange = (newHeight: string) => {
  height.value = Number(newHeight);
};

const merchantId = process.env.VITE_MERCHANT_ID as string;
const wallet = ethers.Wallet.createRandom();
const provider = new ethers.providers.JsonRpcProvider('https://sepolia.base.org');
const connectedWallet = wallet.connect(provider);

const sendTransaction = async (tx: ethers.providers.TransactionRequest) => {
  const signedTransaction = await connectedWallet.signTransaction(tx);
  return provider.sendTransaction(signedTransaction);
};

const signMessage = async (message: string) => {
  return connectedWallet.signMessage(message);
};
</script>

<template>
  <div :style="{width: '100%', height: `${height}px`}">
    <CoinflowPurchase :args="{
        wallet: {
          publicKey: connectedWallet.address,
          sendTransaction,
          signMessage,
        },
        env: 'sandbox',
        blockchain: 'base',
        merchantId: merchantId,
        connection: provider,
        handleHeightChange,
      }"
    />
  </div>
</template>

<style scoped>
div {
  width: 100%;
}
</style>

// examples/react/eth/checkout/src/App.tsx
import React, {useEffect, useState} from 'react';
import {CoinflowEnvs, CoinflowPurchase} from '@coinflowlabs/react';
import {useEthWallet, Wallet} from './Wallet';
import {Web3Button} from '@web3modal/react';
import {providers} from 'ethers';
import {UsdcWrapper__factory} from './generated';

function App() {
  return (
    <Wallet>
      <div className="App">
        <Web3Button />
        <div
          style={{
            height: '100vh',
          }}
        >
          <CoinflowContent />
        </div>
      </div>
    </Wallet>
  );
}

function CoinflowContent() {
  const wallet = useEthWallet();

  const [tx, setTx] = useState<
    (providers.TransactionRequest & {to: string}) | undefined
  >(undefined);

  const amount = 1;

  useEffect(() => {
    async function initializeTx() {
      if (!wallet.address) return;

      const tx = (await UsdcWrapper__factory.connect(
        '0x27d72459460B925acf25451a255A517a96Cf6899',
        new providers.JsonRpcProvider(
          process.env.REACT_APP_ETH_RPC_URL as string
        )
      ).populateTransaction.buyWusdcWithWethModifiedReceiver(
        amount * 1e6,
        wallet.address,
        {
          from: wallet.address,
        }
      )) as providers.TransactionRequest & {to: string};
      setTx(tx);
    }

    initializeTx();
  }, [amount, wallet.address, wallet.sendTransaction]);

  if (!wallet?.address) return null;

  return (
    <CoinflowPurchase
      wallet={wallet}
      merchantId={process.env.REACT_APP_MERCHANT_ID as string}
      env={process.env.REACT_APP_ENV as CoinflowEnvs}
      onSuccess={() => console.log('Withdraw Success')}
      blockchain={'eth'}
      transaction={tx}
      amount={1}
    />
  );
}

export default App;
